### ISSUE TITLE
question: long roadmap for multi-versioned compatible for generator

### ISSUE THREAD

**Issue by NguyenDuck** [lancelotF/ModEx#4]
I would like to inquire about the long-term roadmap for ensuring multi-version compatibility within the generator. Specifically, im interested in understanding the following aspects:

1. **Version Compatibility Strategy:**
   - How does the generator plan to handle compatibility across multiple versions depend on format version?
   - Are there specific guidelines or policies in place to manage versioning and ensure backward compatibility?

2. **Upcoming Features and Enhancements:**
   - What new features and enhancements are planned for future releases that will support multi-version compatibility?
   - Is there a timeline or roadmap available for these updates?

3. **Documentation:**
   - Will there be comprehensive documentation provided to guide users through the process of maintaining compatibility across versions?

I appreciate any insights or information you can provide regarding the long-term plans for multi-version compatibility within the generator. Thank you!

**Comment by lancelotF** [comment]
Hi! Thank you so much for the questions!

First of all I'd like to explain more about generators:

Generators are simple objects that contain data in the most basic way possible. They are added to the core and they tell the core what files to add, what data do these files contain and where to put the files.

With this in mind, generators can do really anything, from building JSON files, to creating textures.

Currently we ship ModExpedite with a few generators:

- Manifest Generator
- Terrain Texture Generator
- Model Generator
- Block Generator

So generators simply tell the framework what to build. On top of generators, we made **factories**, which are wrappers that help developers add complex functions. For example, the current [BlockFactory](https://github.com/lancelotF/ModEx/blob/main/src/factories/blockFactory/BlockFactory.ts) enables developers to create plugins and add them to the block. This plugins what really do is modify the Block Generator. Since most of the functionality will be added through plugins, I believe plugins is what we need to make backward-compatible.

Currently plugins don't have mechanisms to do this, but we plan to adopt a version-aware plugin architecture, where each plugin explicitly declares the format versions it supports and they can even have different behaviors depending on the version.

- Example: A plugin may specify compatibility ranges like ["1.18.0", "1.20.0"].
- If the base generator's version falls outside this range, the framework will throw a clear, actionable error (e.g., "BlockBasicTexturePlugin is incompatible with format version 1.21.0").
- The plugin will be able to recognize the current format version and even handle the functions based on this. For example, if the version is old, it might use old methods to achieve a result.

**About the documentation**
I believe this framework will rely a lot on the community building great plugins, therefore we want to have **the most comprehensive documentation** so users can easily understand how the framework works and how they can build their own plugins, generators and factories. I'm very aware im not gonna be able to achieve a project this big alone, so yes we plan to make comprehensive documentation that explains devs everything about this framework.

If you have any other questions or if I wasn't clear with something I'm happy to hear you! Also suggestions are welcome!

**Comment by lancelotF** [comment]
Marking this as solved since I just created a project and a  [roadmap](https://github.com/users/lancelotF/projects/1/views/1).
